# Site settings
title: Test themes
author: Wferr
baseurl: "/testblog/" # the subpath of your site, e.g. /blog/
url: "https://sairaraza.github.io" # the base hostname & protocol for your site

theme: jekyll-theme-minimal